{"timestamp":"2025-06-05T09:12:18.229155","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-05T09:12:18.231446","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/example_query_sqlserver.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-05T09:12:18.626930Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T09:12:18.627506Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T09:12:18.671305Z","level":"info","event":"Current task name:run_sql_query","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T09:12:18.671752Z","level":"info","event":"Dag name:example_query_sqlserver","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T09:12:18.577530","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-06-05T09:12:18.627860","level":"info","event":"Connection Retrieved 'mssql_edcl'","logger":"airflow.hooks.base"}
{"timestamp":"2025-06-05T09:12:27.973980","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"(20009, b'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\\nNet-Lib error during Connection refused (111)\\nDB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\\nNet-Lib error during Connection refused (111)\\n')","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/example_query_sqlserver.py","lineno":15,"name":"query_sql_server"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":589,"name":"get_records"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":725,"name":"run"},{"filename":"/usr/local/lib/python3.12/contextlib.py","lineno":137,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":832,"name":"_create_autocommit_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py","lineno":103,"name":"get_conn"},{"filename":"/opt/airflow/src/pymssql/_pymssql.pyx","lineno":659,"name":"pymssql._pymssql.connect"}]},{"exc_type":"MSSQLDatabaseException","exc_value":"(20009, b'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\\nNet-Lib error during Connection refused (111)\\nDB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\\nNet-Lib error during Connection refused (111)\\n')","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/src/pymssql/_pymssql.pyx","lineno":650,"name":"pymssql._pymssql.connect"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":2158,"name":"pymssql._mssql.connect"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":712,"name":"pymssql._mssql.MSSQLConnection.__init__"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":1884,"name":"pymssql._mssql.maybe_raise_MSSQLDatabaseException"},{"filename":"/opt/airflow/src/pymssql/_mssql.pyx","lineno":1901,"name":"pymssql._mssql.raise_MSSQLDatabaseException"}]}]}
{"timestamp":"2025-06-05T09:12:28.944980Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T09:12:28.952803Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T09:12:28.955416Z","level":"info","event":"Task:<Task(PythonOperator): run_sql_query>","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T09:12:28.956071Z","level":"info","event":"Failure caused by (20009, b'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\\nNet-Lib error during Connection refused (111)\\nDB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (localhost)\\nNet-Lib error during Connection refused (111)\\n')","chan":"stdout","logger":"task"}
